### ISSUE TITLE
Share on Hugging Face?

### ISSUE THREAD

**Issue by severo** [hyungkwonko/chart-llm#1]
The dataset is awesome! It would be nice to have it on https://huggingface.co/datasets. Do you plan to upload it there?

**Comment by hyungkwonko** [comment]
Thanks @severo for the compliment. Following your suggestion, I have uploaded the dataset here: https://huggingface.co/datasets/hyungkwonko/chart-llm.

Also refer to here to see how to load the data:
https://github.com/hyungkwonko/chart-llm#loading-the-dataset-via-huggingface

**Comment by severo** [comment]
Excellent! Also note that you have a Parquet and a DuckDB version of the dataset in https://huggingface.co/datasets/hyungkwonko/chart-llm/tree/refs%2Fconvert%2Fparquet/default/train.
