### ISSUE TITLE
about the raw data

### ISSUE THREAD

**Issue by Sootung** [hyungkwonko/chart-llm#3]
hello, could you please provide the raw data of NL dataset? Such as png files for image, txt files for L1/L2 captions.

**Comment by hyungkwonko** [comment]
Hi @Sootung ,

Do you mean the charts for the captions?

**Comment by Sootung** [comment]
> Hi @Sootung ,
> 
> Do you mean the charts for the captions?

yes, i can not find charts and captions.

**Comment by hyungkwonko** [comment]
Here is the link to the charts:
https://github.com/hyungkwonko/chart-llm/tree/main/docs/data/chart

Please mind that they are not images, but Vega-Lite specifications, you may visualize and save them as e.g., PNG, using e.g., Vega-Lite editor:
https://vega.github.io/editor/#/edited

We provide sample results of L1/L2 caption, utterance, question for 48 charts that are selected via stratified sampling:
https://github.com/hyungkwonko/chart-llm/tree/main/framework/result

Specifically,
L1: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/l1_description.json
L2: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task1_L23.csv (column: L2)
Utterance: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task2.csv (columns: commands, queries, questions)
Question: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task3.csv (columns: lookup-nonvisual, lookup-visual, compositional-nonvisual, compositional-visual, open-ended)

You can generate more captions using Vega-Lite and our prompting technique:
https://github.com/hyungkwonko/chart-llm#example-nl-dataset-generation

**Comment by Sootung** [comment]
> Here is the link to the charts: https://github.com/hyungkwonko/chart-llm/tree/main/docs/data/chart
> 
> Please mind that they are not images, but Vega-Lite specifications, you may visualize and save them as e.g., PNG, using e.g., Vega-Lite editor: https://vega.github.io/editor/#/edited
> 
> We provide sample results of L1/L2 caption, utterance, question for 48 charts that are selected via stratified sampling: https://github.com/hyungkwonko/chart-llm/tree/main/framework/result
> 
> Specifically, L1: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/l1_description.json L2: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task1_L23.csv (column: L2) Utterance: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task2.csv (columns: commands, queries, questions) Question: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task3.csv (columns: lookup-nonvisual, lookup-visual, compositional-nonvisual, compositional-visual, open-ended)
> 
> You can generate more captions using Vega-Lite and our prompting technique: https://github.com/hyungkwonko/chart-llm#example-nl-dataset-generation

Thanks for your detailed response.

**Comment by FanqingM** [comment]
> Here is the link to the charts: https://github.com/hyungkwonko/chart-llm/tree/main/docs/data/chart
> 
> Please mind that they are not images, but Vega-Lite specifications, you may visualize and save them as e.g., PNG, using e.g., Vega-Lite editor: https://vega.github.io/editor/#/edited
> 
> We provide sample results of L1/L2 caption, utterance, question for 48 charts that are selected via stratified sampling: https://github.com/hyungkwonko/chart-llm/tree/main/framework/result
> 
> Specifically, L1: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/l1_description.json L2: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task1_L23.csv (column: L2) Utterance: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task2.csv (columns: commands, queries, questions) Question: https://github.com/hyungkwonko/chart-llm/blob/main/framework/result/task3.csv (columns: lookup-nonvisual, lookup-visual, compositional-nonvisual, compositional-visual, open-ended)
> 
> You can generate more captions using Vega-Lite and our prompting technique: https://github.com/hyungkwonko/chart-llm#example-nl-dataset-generation

Hello, it seems that it only has questions in task2.csv , if there has the answers to the questions?

**Comment by hyungkwonko** [comment]
No, our work focused on generating questions, but not the answers.
