### ISSUE TITLE
Is there only 48 images?

### ISSUE THREAD

**Issue by FanqingM** [hyungkwonko/chart-llm#4]
Is there only 48 images? can you share me with the total images? Thank you!

**Comment by hyungkwonko** [comment]
Hi @FanqingM,

Thanks for your interests in our work.
You can find 1,981 Vega-Lite specs here: https://github.com/hyungkwonko/chart-llm/tree/main/docs/data/chart.
The specs can be converted into images like PNG via several libraries including this: https://vega.github.io/editor/#/edited
Please check them online as well: https://hyungkwonko.info/chart-llm/explorer.html

Best,
Kwon
